### ISSUE TITLE
I am impressed

### ISSUE THREAD

**Issue by Thomashighbaugh** [frabjous/awesome#1]
Found your configuration via you posting on Reddit (tagging on Github helps :P) and I must say I am thoroughly impressed to see someone else that has figured out to make the libraries and modules they would have to require at the beginning of each file globally scoped within their configuration. That's a rarity my friend, you and I are so far the only people willing to do that with things like `awful` for reasons beyond me as it makes writing the larger style configurations a much more forgiving process overall. 

Anyway, keep up the good work, your configuration is added to my "stars" list and when I finish the "awesome awesomewm modular configurations" list you will be there for sure. Also nice custom color scheme, a dev after my own heart for real.

**Comment by frabjous** [comment]
Thanks! 

Yes originally I had those be local but got tired of all the "require"s in every file, and couldn't think of a reason not to make them global. 

Anyway, I'm closing this as it's not really an "issue" (as far as I can tell).
